import { neon } from '@neondatabase/serverless';
import { issueSignedToken, list, presignUrl } from '@vercel/blob';
import pdfParse from 'pdf-parse';

export const runtime = 'nodejs';
export const maxDuration = 300;

function getSql() {
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL belum tersedia.');
  return neon(process.env.DATABASE_URL);
}

const clean = (v) => String(v || '').replace(/\s+/g, ' ').trim();
const normalize = (v) => clean(v).toLowerCase().replace(/k\s+oordinasi/g,'koordinasi').replace(/s\s+istem/g,'sistem').replace(/z\s+at/g,'zat').replace(/p\s+ewarisan/g,'pewarisan').replace(/listrik\s+,/g,'listrik,').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const compact = (v) => normalize(v).replace(/\s+/g,'');
const STOP = new Set(['yang','dengan','untuk','dari','pada','dalam','manusia','kelas','dan','atau','bagi','serta','oleh','tentang']);
const tokens = (text) => normalize(text).split(' ').filter(x=>x.length>=4&&!STOP.has(x));
const similarity = (a,b) => { const A=new Set(tokens(a)), B=tokens(b); if(!A.size||!B.length)return 0; return B.filter(x=>A.has(x)).length/B.length; };
const isFrontMatter = (text) => { const t=normalize(text); return ['kata pengantar','daftar isi','daftar gambar','daftar tabel','petunjuk penggunaan','glosarium','indeks','biodata penulis','profil penulis','hak cipta','isbn','dilindungi undang undang','kementerian pendidikan','kementerian agama','diterbitkan oleh','prakata','penjelasan fitur buku'].some(x=>t.includes(x)); };
const unitNumber = (v) => { const s=String(v||'').toUpperCase(); if(/^\d+$/.test(s))return Number(s); const m={I:1,II:2,III:3,IV:4,V:5,VI:6,VII:7,VIII:8,IX:9,X:10,XI:11,XII:12}; return m[s]||null; };

function parseUnit(line) {
  const v=clean(line);
  let m=v.match(/^(?:BAB|B\s*A\s*B)\s+([IVXLC]+|\d+)\b\s*(.*)$/i);
  if(m)return{type:'bab',number:unitNumber(m[1]),roman:m[1].toUpperCase(),title:clean(m[2].replace(/\.{2,}/g,' '))};
  m=v.match(/^TEMA\s+([IVXLC]+|\d+)\b\s*(.*)$/i);
  if(m)return{type:'tema',number:unitNumber(m[1]),roman:m[1].toUpperCase(),title:clean(m[2].replace(/\.{2,}/g,' '))};
  return null;
}
const unitHeading = (line) => Boolean(parseUnit(line));
function findTocPage(pages){for(let i=0;i<Math.min(pages.length,80);i++){const p=String(pages[i]||'');if(/daftar\s+isi/i.test(p)||compact(p).includes('daftarisi'))return i;}return -1;}
function parseEntry(line){const v=clean(line);const m=v.match(/^(Bab|B\s*A\s*B|Tema)\s+([IVXLC]+|\d+)\s+(.+?)(?:\s+\.{2,}\s*|\s+…+\s*|\s+—\s*|\s{3,})(\d{1,3})\s*$/i);if(!m)return null;const number=unitNumber(m[2]),printedPage=Number(m[4]);const title=clean(m[3].replace(/\.{2,}|…+/g,' '));if(!number||!printedPage||title.length<3)return null;return{type:/^tema$/i.test(m[1])?'tema':'bab',number,roman:m[2].toUpperCase(),title,printedPage};}
function firstSubFromToc(raw){const m=raw.match(/(?:^|\n)\s*A(?:\.|\))\s+(.{3,180}?)(?:\.{2,}|…+|\s+—\s*|\s{3,})(\d{1,3})\s*(?=\n|$)/im);return m?{title:clean(m[1]),printedPage:Number(m[2])}:null;}
function parseToc(pages){const tocIndex=findTocPage(pages);if(tocIndex<0)return{tocIndex:-1,units:[],tocText:''};const raw=pages.slice(tocIndex,Math.min(pages.length,tocIndex+16)).join('\n').replace(/\u0000/g,' ');const lines=raw.split('\n').map(clean).filter(Boolean);const units=[];for(const line of lines){const e=parseEntry(line);if(e&&!units.some(u=>u.type===e.type&&u.number===e.number))units.push(e);}const flat=raw.replace(/\s+/g,' ');for(const m of flat.matchAll(/(?:Bab|B\s*a\s*b|Tema)\s+([IVXLC]+|\d+)\s+/gi)){const type=/tema/i.test(m[0].split(/\s+/)[0])?'tema':'bab';const n=unitNumber(m[1]);if(!n||units.some(u=>u.type===type&&u.number===n))continue;const start=m.index+m[0].length;const next=flat.slice(start).search(/\s+(?:Bab|B\s*a\s*b|Tema)\s+[IVXLC0-9]+\s+/i);const end=next>=0?start+next:Math.min(start+320,flat.length);const chunk=clean(flat.slice(start,end));const nums=[...chunk.matchAll(/\b(\d{1,3})\b/g)];const last=nums.at(-1);const printedPage=last?Number(last[1]):null;const title=clean((printedPage?chunk.slice(0,last.index):chunk).replace(/\.{2,}|…+/g,' ').replace(/\s+—\s+.*/,' '));if(title.length>=3)units.push({type,number:n,roman:m[1].toUpperCase(),title,printedPage});}return{tocIndex,units:units.sort((a,b)=>a.number-b.number),tocText:raw};}
function findActualUnitPage(pages,tocIndex,unit){const out=[];for(let i=Math.max(0,tocIndex+1);i<pages.length;i++){const text=String(pages[i]||'').trim();if(!text||text.length<120)continue;const normalized=normalize(text);const lines=text.split('\n').map(clean).filter(Boolean);for(const line of lines.slice(0,80)){const e=parseUnit(line);if(!e||e.type!==unit.type||e.number!==unit.number)continue;const sim=similarity(e.title,unit.title);const learning=/tujuan pembelajaran|kata kunci|pertanyaan pemantik|aktivitas pembelajaran|kegiatan pembelajaran/.test(normalized);out.push({page:i+1,title:e.title||unit.title,score:80+sim*30+(learning?10:0)});}const marker=unit.type==='tema'?`tema${unit.number}`:`bab${unit.number}`;const titleSim=similarity(normalized.slice(0,2600),unit.title);if(compact(text).includes(marker)&&titleSim>=0.25)out.push({page:i+1,title:unit.title,score:45+titleSim*40});}out.sort((a,b)=>b.score-a.score||a.page-b.page);return out[0]||null;}
function findActualSubchapterPage(pages,tocIndex,sub){if(!sub?.title)return null;const target=normalize(sub.title),out=[];for(let i=Math.max(0,tocIndex+1);i<pages.length;i++){for(const line of String(pages[i]||'').split('\n').map(clean)){const m=line.match(/^A(?:\.|\))\s+(.{3,180})$/i);if(m){const sim=similarity(m[1],target);if(sim>=0.55)out.push({page:i+1,title:clean(m[1]),score:sim*100});}}}out.sort((a,b)=>b.score-a.score||a.page-b.page);return out[0]||null;}
function findFirstSubchapter(pages,unitPage){for(let i=Math.max(0,unitPage-1);i<Math.min(pages.length,unitPage+30);i++){for(const line of String(pages[i]||'').split('\n').map(clean).filter(Boolean)){if(isFrontMatter(line)||/^(ayo\s+uji|aktivitas|projek|proyek|pengayaan|remedial|refleksi|rangkuman|evaluasi|asesmen|glosarium|kata kunci|tujuan pembelajaran)/i.test(line))continue;const m=line.match(/^([A-Z])(?:\.|\))\s+(.{4,180})$/);if(m&&!/^\d/.test(m[2]))return{label:m[1].toUpperCase(),title:clean(m[2]),page:i+1};}}return null;}
function scanFirstUnit(pages,start=4){for(let i=Math.max(0,start);i<Math.min(pages.length,180);i++){for(const line of String(pages[i]||'').split('\n').map(clean).filter(Boolean)){const e=parseUnit(line);if(e&&e.number===1&&!isFrontMatter(line))return{page:i+1,type:e.type,title:e.title,roman:e.roman,score:60};}}return null;}
function findFirstRealUnit(pages){const toc=parseToc(pages);const first=toc.units.find(u=>u.number===1);if(!first){const scanned=scanFirstUnit(pages,toc.tocIndex>=0?toc.tocIndex+1:4);if(!scanned)return{page:1,unit:'Materi berikutnya',score:0,source:'fallback',subchapter:null};return{page:scanned.page,unit:`${scanned.type==='tema'?'Tema':'Bab'} ${scanned.roman} ${scanned.title}`,score:scanned.score,source:'unit_scan_fallback',tocIndex:toc.tocIndex>=0?toc.tocIndex+1:null,tocPrintedPage:null,subchapter:findFirstSubchapter(pages,scanned.page)};}const actual=findActualUnitPage(pages,toc.tocIndex,first);const tocSub=firstSubFromToc(toc.tocText);const actualSub=tocSub?findActualSubchapterPage(pages,toc.tocIndex,tocSub):null;const page=actual?.page||actualSub?.page;if(!page){const scanned=scanFirstUnit(pages,toc.tocIndex+1);if(scanned)return{page:scanned.page,unit:`${scanned.type==='tema'?'Tema':'Bab'} ${scanned.roman} ${scanned.title}`,score:scanned.score,source:'unit_scan_fallback',tocIndex:toc.tocIndex+1,tocPrintedPage:first.printedPage,subchapter:findFirstSubchapter(pages,scanned.page)};return{page:1,unit:'Materi berikutnya',score:0,source:'fallback',subchapter:null};}const sub=actualSub?{label:'A',title:actualSub.title,page:actualSub.page}:findFirstSubchapter(pages,page);return{page,unit:`${first.type==='tema'?'Tema':'Bab'} ${first.roman} ${first.title}`,score:actual?.score||55,source:'table_of_contents',tocIndex:toc.tocIndex+1,tocPrintedPage:first.printedPage,subchapter:sub};}
function findNextSelection(pages){const first=findFirstRealUnit(pages),sub=first.subchapter||findFirstSubchapter(pages,first.page);return{unit:first.unit,subbab:sub?`${sub.label}. ${sub.title}`:'Subbab berikutnya',unitPage:first.page,subchapterPage:sub?.page||first.page};}
function baseFileName(name){return String(name||'').split(/[\\/]/).pop().replace(/\.[^.]+$/,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function filenameMatches(pathname,originalName){const a=baseFileName(pathname),b=baseFileName(originalName);return Boolean(a&&b&&a.includes(b));}
async function resolveBlob(sql,book,mapel,kelas){const prefix=`books/${mapel}/${kelas}/`;if(book.blob_path){try{const d=await issueSignedToken({pathname:book.blob_path,operations:['get'],validUntil:Date.now()+300000,storeId:process.env.BLOB_STORE_ID});const s=await presignUrl(d,{operation:'get',pathname:book.blob_path,access:'private',validUntil:Date.now()+120000,useCache:false});const probe=await fetch(s.presignedUrl,{method:'HEAD',cache:'no-store'});if(probe.ok)return{pathname:book.blob_path,source:'database'};}catch{}}const inv=await list({prefix,limit:1000});const matches=inv.blobs.filter(b=>filenameMatches(b.pathname,book.file_name)).sort((a,b)=>new Date(b.uploadedAt).getTime()-new Date(a.uploadedAt).getTime());if(!matches.length)throw new Error(`Blob tidak ditemukan di folder ${prefix} dengan nama yang cocok dengan ${book.file_name}.`);const actual=matches[0];await sql`UPDATE books SET blob_path=${actual.pathname},blob_url=${actual.url||''},file_size=${Number(actual.size)||0},updated_at=NOW() WHERE id=${book.id}`;return{pathname:actual.pathname,source:'blob_inventory'};}
async function loadPdf(pathname){const storeId=process.env.BLOB_STORE_ID;const oidcToken=process.env.VERCEL_OIDC_TOKEN;if(!storeId)throw new Error('BLOB_STORE_ID belum tersedia di environment Vercel.');const d=await issueSignedToken({pathname,operations:['get'],validUntil:Date.now()+600000,...(oidcToken?{oidcToken}:{}),storeId});const s=await presignUrl(d,{operation:'get',pathname,access:'private',validUntil:Date.now()+300000,useCache:false});const r=await fetch(s.presignedUrl,{cache:'no-store'});if(!r.ok)throw new Error(`Blob GET HTTP ${r.status} untuk pathname aktual ${pathname}.`);return Buffer.from(await r.arrayBuffer());}
async function extractPages(buffer){const pages=[];const pagerender=async pageData=>{const tc=await pageData.getTextContent({normalizeWhitespace:true,disableCombineTextItems:false});const lines=[];let current='',lastY=null;for(const item of tc.items||[]){const str=String(item.str||'');if(!str)continue;const y=item.transform?.[5];if(current&&lastY!==null&&typeof y==='number'&&Math.abs(y-lastY)>4){lines.push(clean(current));current='';}current+=`${current?' ':''}${str}`;lastY=typeof y==='number'?y:lastY;if(item.hasEOL){lines.push(clean(current));current='';}}if(current)lines.push(clean(current));const text=lines.filter(Boolean).join('\n').trim();pages.push(text);return text;};const parsed=await pdfParse(buffer,{pagerender});const totalPages=Number(parsed.numpages)||pages.length;if(!totalPages)throw new Error('PDF tidak memiliki halaman yang terbaca.');return{pages,totalPages,totalTextCharacters:pages.reduce((n,p)=>n+p.length,0)};}
async function readTask(sql,task){if(!task.requires_book)return{task_id:task.task_id,status:'not_required',reason:'Task ini tidak membutuhkan buku pegangan.'};const kelas=task.jenis_kegiatan==='Ekstrakurikuler'?'-':task.kelas;const books=await sql`SELECT * FROM books WHERE aktif=TRUE AND mapel=${task.mapel} AND kelas=${kelas} ORDER BY created_at DESC LIMIT 1`;if(!books.length)return{task_id:task.task_id,status:'book_missing',reason:`Tidak ada buku untuk ${task.mapel} ${kelas}.`};const book=books[0],actual=await resolveBlob(sql,book,task.mapel,kelas);const previous=await sql`SELECT * FROM progress WHERE sekolah=${task.sekolah} AND mapel=${task.mapel} AND kelas=${kelas} LIMIT 1`;const progress=previous[0]||null;const previousEndPage=Number(progress?.halaman_akhir||0);const buffer=await loadPdf(actual.pathname);if(buffer.subarray(0,5).toString()!=='%PDF-')throw new Error(`Objek Blob bukan PDF valid: ${book.file_name}`);const{pages,totalPages,totalTextCharacters}=await extractPages(buffer);const firstUnit=findFirstRealUnit(pages);const safeStart=Math.min(Math.max(1,previousEndPage>0?previousEndPage+1:firstUnit.page),totalPages),safeEnd=Math.min(totalPages,safeStart+3),selection=findNextSelection(pages),excerpt=pages.slice(safeStart-1,safeEnd).join('\n').replace(/\s+/g,' ').trim().slice(0,3000);await sql`UPDATE tasks SET status='book_ready',book_path=${actual.pathname},error_message='',updated_at=NOW() WHERE task_id=${task.task_id}`;return{task_id:task.task_id,status:'success',blob_resolution:actual.source,blob_path:actual.pathname,sekolah:task.sekolah,mapel:task.mapel,kelas,pertemuan:task.pertemuan_berikutnya,buku:book.nama_buku,file_name:book.file_name,extraction_method:'pdf-parse-pagerender',total_halaman:totalPages,total_text_characters:totalTextCharacters,halaman_awal:safeStart,halaman_akhir:safeEnd,first_content_page:firstUnit.page,front_matter_pages:Math.max(0,firstUnit.page-1),first_content_chapter:firstUnit.unit,content_detection_score:firstUnit.score,content_detection_signals:{hasLearningSignals:/tujuan pembelajaran|kata kunci|pertanyaan pemantik|aktivitas pembelajaran|kegiatan pembelajaran/i.test(String(pages[firstUnit.page-1]||'')),nextSubstantive:String(pages[firstUnit.page]||'').length>=600},content_locator_source:firstUnit.source,toc_index_page:firstUnit.tocIndex||null,toc_printed_page:firstUnit.tocPrintedPage||null,preview_halaman:pages.slice(firstUnit.page-1,firstUnit.page+2).map((text,i)=>({halaman:firstUnit.page+i,karakter:text.length,cuplikan:text.slice(0,700)})),bab:selection.unit,subbab:selection.subbab,halaman_bab:selection.unitPage,halaman_subbab:selection.subchapterPage,materi_excerpt:excerpt,previous_progress:{bab_terakhir:progress?.bab_terakhir||'',subbab_terakhir:progress?.subbab_terakhir||'',halaman_akhir:previousEndPage,materi_terakhir:progress?.materi_terakhir||''}};}
export async function POST(request){try{const body=await request.json().catch(()=>({}));const sql=getSql();const taskId=body.task_id?String(body.task_id):null;const tanggal=body.tanggal?String(body.tanggal):null;if(!taskId&&!tanggal)return Response.json({agent:'book_reader',status:'error',reason:'Kirim task_id atau tanggal.'},{status:400});const tasks=taskId?await sql`SELECT * FROM tasks WHERE task_id=${taskId} LIMIT 1`:await sql`SELECT * FROM tasks WHERE tanggal=${tanggal} AND status IN ('progress_ready','book_ready','book_error') ORDER BY jam_mulai NULLS LAST, task_id`;if(!tasks.length)return Response.json({agent:'book_reader',status:'no_tasks',tanggal,tasks:[]});const results=[];for(const task of tasks){try{results.push(await readTask(sql,task));}catch(e){const message=e instanceof Error?e.message:'Book Reader gagal membaca PDF.';await sql`UPDATE tasks SET status='book_error',error_message=${message},updated_at=NOW() WHERE task_id=${task.task_id}`;results.push({task_id:task.task_id,status:'error',error:message});}}return Response.json({agent:'book_reader',status:'success',tanggal:tanggal||tasks[0]?.tanggal,tasks:results});}catch(e){return Response.json({agent:'book_reader',status:'error',reason:e instanceof Error?e.message:'Book Reader gagal dijalankan.'},{status:500});}}
